
## keys for twitter developer

CONSUMER_KEY = "ViwmDmLXGkcwKENpasfBZQ9kc"
CONSUMER_SECRET = "KufWqJpPsinfcTCzdcQHVktGqGfuEpXFq30ui69Y44gmrzUIMq"
ACCESS_TOKEN_KEY = "531951403-JKSzHy4ObVL8JXujz0uwyHjrLYqUgQvbbqmNaRzq"
ACCESS_TOKEN_SECRET = "uirENDGmCuTpq7G2HyPSAxteOSfRFUWFUkGLCX5ZuUKgv"
